# Generated by Django 4.1.4 on 2023-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
